# Generated by Django 2.1.7 on 2019-04-04 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assetinformation',
            fields=[
                ('asset_id', models.AutoField(db_column='ASSET_ID', primary_key=True, serialize=False)),
                ('atype', models.IntegerField(db_column='ATYPE')),
                ('asset_no', models.IntegerField(blank=True, null=True)),
                ('beg_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('well_id', models.IntegerField(blank=True, null=True)),
                ('tract_id', models.IntegerField(blank=True, null=True)),
                ('mineral_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'assetinformation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Assetname',
            fields=[
                ('asset_name_id', models.AutoField(db_column='Asset_name_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='NAME', max_length=50)),
                ('asset_no', models.IntegerField(db_column='ASSET_NO')),
            ],
            options={
                'db_table': 'assetname',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Assettype',
            fields=[
                ('asset_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('asset_type', models.IntegerField()),
                ('asset_name', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'assettype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('bid_id', models.AutoField(db_column='BID_ID', primary_key=True, serialize=False)),
                ('sdate', models.DateTimeField()),
                ('sexpire', models.DateTimeField()),
                ('svalue', models.FloatField(blank=True, null=True)),
                ('state', models.IntegerField()),
                ('bidder', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bid',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cust_id', models.AutoField(db_column='CUST_ID', primary_key=True, serialize=False)),
                ('cust_fname', models.CharField(db_column='CUST_FNAME', max_length=50)),
                ('cust_lname', models.CharField(db_column='CUST_LNAME', max_length=50)),
                ('cust_no', models.CharField(db_column='CUST_NO', max_length=50)),
                ('sign_date', models.DateField(blank=True, db_column='SIGN_DATE', null=True)),
                ('image', models.TextField(blank=True, db_column='IMAGE', null=True)),
                ('email', models.CharField(blank=True, db_column='EMAIL', max_length=50, null=True)),
                ('credit', models.FloatField(blank=True, db_column='CREDIT', null=True)),
                ('phone', models.CharField(blank=True, db_column='PHONE', max_length=50, null=True)),
                ('cust_address1', models.CharField(blank=True, db_column='CUST_ADDRESS1', max_length=50, null=True)),
                ('cust_address2', models.CharField(blank=True, db_column='CUST_ADDRESS2', max_length=50, null=True)),
                ('cust_city', models.CharField(blank=True, db_column='CUST_CITY', max_length=50, null=True)),
                ('cust_zipcode', models.CharField(blank=True, db_column='CUST_ZIPCODE', max_length=10, null=True)),
                ('cust_state', models.CharField(blank=True, db_column='CUST_STATE', max_length=2, null=True)),
                ('user_name', models.CharField(blank=True, max_length=32, null=True)),
                ('title', models.CharField(blank=True, db_column='Title', max_length=16, null=True)),
                ('mobile', models.CharField(blank=True, db_column='Mobile', max_length=32, null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dblistings',
            fields=[
                ('sale_id', models.AutoField(db_column='SALE_ID', primary_key=True, serialize=False)),
                ('ondate', models.DateField()),
                ('sexpire', models.DateField()),
                ('askvalue', models.FloatField(blank=True, null=True)),
                ('state', models.IntegerField()),
                ('bidid', models.IntegerField(blank=True, null=True)),
                ('soldvalue', models.FloatField(blank=True, null=True)),
                ('solddate', models.DateField(blank=True, null=True)),
                ('soldto', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dblistings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Leasestable',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tract_id', models.CharField(blank=True, db_column='Tract ID', max_length=4, null=True)),
                ('lease', models.CharField(blank=True, db_column='Lease', max_length=3, null=True)),
                ('tract_name', models.CharField(blank=True, db_column='Tract Name', max_length=4, null=True)),
                ('partial', models.CharField(blank=True, db_column='Partial', max_length=1, null=True)),
                ('gross_acres', models.IntegerField(blank=True, db_column='Gross Acres', null=True)),
                ('net_acres', models.IntegerField(blank=True, db_column='Net Acres', null=True)),
                ('legal_description', models.CharField(blank=True, db_column='Legal Description', max_length=106, null=True)),
                ('county', models.CharField(blank=True, db_column='County', max_length=9, null=True)),
                ('state', models.CharField(blank=True, db_column='State', max_length=9, null=True)),
                ('township', models.CharField(blank=True, db_column='Township', max_length=10, null=True)),
                ('lrange', models.CharField(blank=True, db_column='LRange', max_length=10, null=True)),
                ('section', models.CharField(blank=True, db_column='Section', max_length=10, null=True)),
                ('quarter_call', models.CharField(blank=True, db_column='Quarter Call', max_length=10, null=True)),
                ('abstract', models.CharField(blank=True, db_column='Abstract', max_length=10, null=True)),
                ('block', models.CharField(blank=True, db_column='Block', max_length=10, null=True)),
                ('lot', models.CharField(blank=True, db_column='Lot', max_length=10, null=True)),
                ('survey', models.CharField(blank=True, db_column='Survey', max_length=10, null=True)),
            ],
            options={
                'db_table': 'leasestable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Minerallocations',
            fields=[
                ('wid', models.AutoField(primary_key=True, serialize=False)),
                ('mtype', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, db_column='NAME', max_length=64, null=True)),
                ('x_latt', models.FloatField(blank=True, null=True)),
                ('x_long', models.FloatField(blank=True, null=True)),
                ('x_depth', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'minerallocations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('owner_id', models.AutoField(db_column='OWNER_ID', primary_key=True, serialize=False)),
                ('puch_date', models.DateField()),
                ('sold_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ownership',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Royalties',
            fields=[
                ('rid', models.AutoField(db_column='Rid', primary_key=True, serialize=False)),
                ('operator_name', models.CharField(blank=True, db_column='Operator_Name', max_length=64, null=True)),
                ('owner_name', models.CharField(blank=True, db_column='Owner_Name', max_length=64, null=True)),
                ('owner_number', models.IntegerField(blank=True, db_column='Owner_Number', null=True)),
                ('check_number', models.CharField(blank=True, db_column='Check_Number', max_length=32, null=True)),
                ('check_date', models.DateField(blank=True, db_column='Check_Date', null=True)),
                ('check_amount', models.FloatField(blank=True, db_column='Check_Amount', null=True)),
                ('operator_cc', models.CharField(blank=True, db_column='Operator_CC', max_length=32, null=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=128, null=True)),
                ('product_code', models.CharField(blank=True, db_column='Product_Code', max_length=32, null=True)),
                ('interest_type', models.CharField(blank=True, db_column='Interest_Type', max_length=32, null=True)),
                ('owner_percent', models.FloatField(blank=True, db_column='Owner_Percent', null=True)),
                ('dist_pct', models.FloatField(blank=True, db_column='Dist_pct', null=True)),
                ('prod_date', models.DateField(blank=True, db_column='Prod_Date', null=True)),
                ('price', models.FloatField(blank=True, db_column='Price', null=True)),
                ('btu_factor', models.FloatField(blank=True, db_column='BTU_Factor', null=True)),
                ('gross_volume', models.FloatField(blank=True, db_column='Gross_Volume', null=True)),
                ('gross_value', models.FloatField(blank=True, db_column='Gross_Value', null=True)),
                ('gross_taxes', models.FloatField(blank=True, db_column='Gross_Taxes', null=True)),
                ('gross_deducts', models.FloatField(blank=True, db_column='Gross_Deducts', null=True)),
                ('net_value', models.FloatField(blank=True, db_column='Net_Value', null=True)),
                ('owner_volume', models.FloatField(blank=True, db_column='Owner_Volume', null=True)),
                ('owner_value', models.FloatField(blank=True, db_column='Owner_Value', null=True)),
                ('owner_taxes', models.FloatField(blank=True, db_column='Owner_Taxes', null=True)),
                ('owner_deducts', models.FloatField(blank=True, db_column='Owner_Deducts', null=True)),
                ('owner_net_value', models.FloatField(blank=True, db_column='Owner_Net_Value', null=True)),
                ('tax_type_1', models.CharField(blank=True, db_column='Tax_Type_1', max_length=16, null=True)),
                ('gross_tax_1', models.FloatField(blank=True, db_column='Gross_Tax_1', null=True)),
                ('net_tax_1', models.FloatField(blank=True, db_column='Net_Tax_1', null=True)),
            ],
            options={
                'db_table': 'royalties',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tractlocations',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('tract_id', models.IntegerField(blank=True, null=True)),
                ('x_latt', models.FloatField(blank=True, null=True)),
                ('x_long', models.FloatField(blank=True, null=True)),
                ('x_depth', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tractlocations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tractnames',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('tract_id', models.IntegerField(blank=True, null=True)),
                ('tract_name', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'tractnames',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tractstable',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tract_id', models.CharField(blank=True, db_column='Tract ID', max_length=4, null=True)),
                ('gross_acres', models.DecimalField(blank=True, db_column='Gross Acres', decimal_places=7, max_digits=10, null=True)),
                ('net_mineral_acres', models.DecimalField(blank=True, db_column='Net Mineral Acres', decimal_places=4, max_digits=6, null=True)),
                ('net_interest_decimal', models.DecimalField(blank=True, db_column='Net Interest Decimal', decimal_places=5, max_digits=6, null=True)),
                ('net_fractional_interest', models.CharField(blank=True, db_column='Net Fractional Interest', max_length=10, null=True)),
                ('net_royalty_acres', models.DecimalField(blank=True, db_column='Net Royalty Acres', decimal_places=2, max_digits=5, null=True)),
                ('legal_description', models.CharField(blank=True, db_column='Legal Description', max_length=298, null=True)),
                ('county', models.CharField(blank=True, db_column='County', max_length=10, null=True)),
                ('state', models.CharField(blank=True, db_column='State', max_length=12, null=True)),
                ('township', models.CharField(blank=True, db_column='Township', max_length=4, null=True)),
                ('trange', models.CharField(blank=True, db_column='tRange', max_length=4, null=True)),
                ('section', models.CharField(blank=True, db_column='Section', max_length=3, null=True)),
                ('quarter_call', models.CharField(blank=True, db_column='Quarter Call', max_length=8, null=True)),
                ('abstract', models.CharField(blank=True, db_column='Abstract', max_length=10, null=True)),
                ('block', models.CharField(blank=True, db_column='Block', max_length=8, null=True)),
                ('lot', models.CharField(blank=True, db_column='Lot', max_length=10, null=True)),
                ('survey', models.CharField(blank=True, db_column='Survey', max_length=14, null=True)),
                ('abbreviated_legal_description', models.CharField(blank=True, db_column='Abbreviated Legal Description', max_length=33, null=True)),
                ('comments', models.CharField(blank=True, db_column='Comments', max_length=274, null=True)),
                ('interest_type', models.CharField(blank=True, db_column='Interest Type', max_length=4, null=True)),
                ('all_depths', models.CharField(blank=True, db_column='All Depths', max_length=1, null=True)),
                ('depth_notes', models.CharField(blank=True, db_column='Depth Notes', max_length=14, null=True)),
                ('leased', models.CharField(blank=True, db_column='Leased', max_length=1, null=True)),
                ('surface_ownership', models.CharField(blank=True, db_column='Surface Ownership', max_length=1, null=True)),
                ('deed_doc_name_1', models.CharField(blank=True, db_column='Deed Doc Name #1', max_length=13, null=True)),
                ('deed_doc_name_2', models.CharField(blank=True, db_column='Deed Doc Name #2', max_length=14, null=True)),
            ],
            options={
                'db_table': 'tractstable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Welllocations',
            fields=[
                ('wid', models.AutoField(primary_key=True, serialize=False)),
                ('well_id', models.IntegerField(blank=True, null=True)),
                ('x_latt', models.FloatField(blank=True, null=True)),
                ('x_long', models.FloatField(blank=True, null=True)),
                ('x_depth', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'welllocations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wellnames',
            fields=[
                ('wid', models.AutoField(primary_key=True, serialize=False)),
                ('well_id', models.IntegerField(blank=True, null=True)),
                ('well_name', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'wellnames',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wells',
            fields=[
                ('wid', models.AutoField(primary_key=True, serialize=False)),
                ('well_api', models.CharField(blank=True, max_length=16, null=True)),
                ('well_type', models.IntegerField(blank=True, null=True)),
                ('well_long', models.FloatField(blank=True, null=True)),
                ('well_latt', models.FloatField(blank=True, null=True)),
                ('depth', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wells',
                'managed': False,
            },
        ),
    ]
