# Generated by Django 2.1.7 on 2019-04-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edlm', '0002_auto_20190411_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='royalties',
            name='document',
            field=models.FileField(blank=True, db_column='Document', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='royalties',
            name='user_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
